// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUI_FDM.PageObjects.MeetingMinutesFormPage.MeetingMinutesPageClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class MeetingMinutesPage
    {
        
        #region Properties
        public UIFormDetailsInternetEWindow UIFormDetailsInternetEWindow
        {
            get
            {
                if ((this.mUIFormDetailsInternetEWindow == null))
                {
                    this.mUIFormDetailsInternetEWindow = new UIFormDetailsInternetEWindow();
                }
                return this.mUIFormDetailsInternetEWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIFormDetailsInternetEWindow mUIFormDetailsInternetEWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFormDetailsInternetEWindow : BrowserWindow
    {
        
        public UIFormDetailsInternetEWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Form Details - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Form Details - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIFormDetailsDocument UIFormDetailsDocument
        {
            get
            {
                if ((this.mUIFormDetailsDocument == null))
                {
                    this.mUIFormDetailsDocument = new UIFormDetailsDocument(this);
                }
                return this.mUIFormDetailsDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIFormDetailsDocument mUIFormDetailsDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIFormDetailsDocument : HtmlDocument
    {
        
        public UIFormDetailsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Form Details";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://qa-projectforms-eus.cloudapp.net/#/forms/DynamicSchema/d347a315-54ca-46d3" +
                "-bce7-9d78d3fe4cea/Meetings/221ba91f-739a-40d9-afc2-8ec9138df5c7";
            this.WindowTitles.Add("Form Details - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDateEdit
        {
            get
            {
                if ((this.mUIDateEdit == null))
                {
                    this.mUIDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Datepicker1Input_1";
                    this.mUIDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Meeting__x0020__Date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "date-form-control form-control ng-pristine ng-untouched ng-valid k-input ng-valid" +
                        "-validate-date";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Meeting__x0020__Date\" class=\"date-";
                    this.mUIDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIDateEdit.WindowTitles.Add("Form Details - Internet Explorer");
                    #endregion
                }
                return this.mUIDateEdit;
            }
        }
        
        public HtmlEdit UINumberEdit
        {
            get
            {
                if ((this.mUINumberEdit == null))
                {
                    this.mUINumberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINumberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "TextBox2Input_1";
                    this.mUINumberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Meeting__x0020__Number";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control ng-pristine ng-untouched ng-valid";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Meeting__x0020__Number\" class=\"for";
                    this.mUINumberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUINumberEdit.WindowTitles.Add("Form Details - Internet Explorer");
                    #endregion
                }
                return this.mUINumberEdit;
            }
        }
        
        public HtmlEdit UISubjectEdit
        {
            get
            {
                if ((this.mUISubjectEdit == null))
                {
                    this.mUISubjectEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "TextBox1Input_1";
                    this.mUISubjectEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Subject";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control ng-pristine ng-untouched ng-valid";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Subject\" class=\"form-control ng-pr";
                    this.mUISubjectEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUISubjectEdit.WindowTitles.Add("Form Details - Internet Explorer");
                    #endregion
                }
                return this.mUISubjectEdit;
            }
        }
        
        public HtmlEdit UILocationEdit
        {
            get
            {
                if ((this.mUILocationEdit == null))
                {
                    this.mUILocationEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "TextBox3Input_1";
                    this.mUILocationEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Location";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control ng-pristine ng-untouched ng-valid";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Location\" class=\"form-control ng-p";
                    this.mUILocationEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUILocationEdit.WindowTitles.Add("Form Details - Internet Explorer");
                    #endregion
                }
                return this.mUILocationEdit;
            }
        }
        
        public UIUserList1_1Custom UIUserList1_1Custom
        {
            get
            {
                if ((this.mUIUserList1_1Custom == null))
                {
                    this.mUIUserList1_1Custom = new UIUserList1_1Custom(this);
                }
                return this.mUIUserList1_1Custom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDateEdit;
        
        private HtmlEdit mUINumberEdit;
        
        private HtmlEdit mUISubjectEdit;
        
        private HtmlEdit mUILocationEdit;
        
        private UIUserList1_1Custom mUIUserList1_1Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIUserList1_1Custom : HtmlCustom
    {
        
        public UIUserList1_1Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "UserList1_1";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "dir-user-list";
            this.FilterProperties["Class"] = "flow-layout ng-isolate-scope";
            this.FilterProperties["ControlDefinition"] = "class=\"flow-layout ng-isolate-scope\" id=";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Form Details - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIItemEdit.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "k-input kendo-form-control ng-pristine ng-untouched ng-valid";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "tabindex=\"0\" title=\"\" class=\"k-input ken";
                    this.mUIItemEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIItemEdit.WindowTitles.Add("Form Details - Internet Explorer");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIItemEdit;
        #endregion
    }
}
